# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-03 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JdAccessories',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('material', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=50, null=True)),
                ('producturl', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'jd_accessories',
            },
        ),
        migrations.CreateModel(
            name='JdBags',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('number', models.CharField(max_length=300, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('producturl', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('element', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'jd_bags',
            },
        ),
        migrations.CreateModel(
            name='JdBeautyMakeup',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('effect', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('wherefrom', models.CharField(max_length=200, null=True)),
                ('skin', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'jd_beautymakeup',
            },
        ),
        migrations.CreateModel(
            name='JdBelt',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=100, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('style', models.CharField(max_length=20, null=True)),
                ('producturl', models.CharField(max_length=100, null=True)),
                ('origin', models.CharField(max_length=50, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'jd_belt',
            },
        ),
        migrations.CreateModel(
            name='JdCloth',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('producturl', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'jd_cloth',
            },
        ),
        migrations.CreateModel(
            name='JdDecoration',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('origin', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('producturl', models.CharField(max_length=100, null=True)),
                ('material', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'jd_decoration',
            },
        ),
        migrations.CreateModel(
            name='JdShoe',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=100, null=True)),
                ('producturl', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'jd_shoe',
            },
        ),
        migrations.CreateModel(
            name='JdWallet',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('material', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('producturl', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'jd_wallet',
            },
        ),
        migrations.CreateModel(
            name='mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('title2', models.CharField(max_length=20, null=True)),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FindApp.mall')),
            ],
            options={
                'db_table': 'malls',
            },
        ),
        migrations.CreateModel(
            name='SkAccessories',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('productproperties', models.CharField(max_length=200, null=True)),
                ('producturl', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'sk_accessories',
            },
        ),
        migrations.CreateModel(
            name='SkBags',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('ApplicablePeople', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'sk_bag',
            },
        ),
        migrations.CreateModel(
            name='SkBeautyMakeup',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('people', models.CharField(max_length=200, null=True)),
                ('shelflife', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('scenario', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('efficacy', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('skin', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'sk_beautymakeup',
            },
        ),
        migrations.CreateModel(
            name='SkCloth',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'sk_cloth',
            },
        ),
        migrations.CreateModel(
            name='SkJewellery',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('materialproperties', models.CharField(max_length=200, null=True)),
                ('producturl', models.CharField(max_length=200, null=True)),
                ('productproperties', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('origin', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'sk_jewellery',
            },
        ),
        migrations.CreateModel(
            name='TmBags',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=200, null=True)),
                ('sex', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('color', models.TextField(null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tm_bag',
            },
        ),
        migrations.CreateModel(
            name='TmBeautyMakeup',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('shelf', models.CharField(max_length=200, null=True)),
                ('datelimit', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('effect', models.CharField(max_length=200, null=True)),
                ('skin', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tm_beautymakeup',
            },
        ),
        migrations.CreateModel(
            name='TmColth',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('size', models.TextField(null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('color', models.TextField(null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('kuanshi', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tm_colth',
            },
        ),
        migrations.CreateModel(
            name='TmJewelry',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=200, null=True)),
                ('appraisaltype', models.CharField(max_length=200, null=True)),
                ('vicegrade', models.CharField(max_length=200, null=True)),
                ('specifications', models.TextField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('appraisalmarks', models.CharField(max_length=200, null=True)),
                ('paragraph', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('certificationmark', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('use', models.CharField(max_length=200, null=True)),
                ('maingrade', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tm_jewelry',
            },
        ),
        migrations.CreateModel(
            name='TmShoe',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('color', models.TextField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('people', models.CharField(max_length=200, null=True)),
                ('kuansi', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tm_shoe',
            },
        ),
    ]
